name: Generate Snake

# Controls when the action runs
on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch: # allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Generate the snake SVG
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: kaiseldev-sudo
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push the SVG to the 'output' branch
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
